"""
SQLite-backed secrets store for operator-managed credentials, with AES-256-GCM
encryption at rest by default.

Threading: each call opens its own short-lived connection so the store is
safe to use from both the dashboard request threads and the background
sync task. SQLite handles serialization at the file level.

Storage location: ``~/.serena/secrets.sqlite3`` (or the path passed to
``SecretsStore(path=...)``). The parent directory is created with mode 700
and the database file with mode 600 on first creation.

Encryption is opt-out, not opt-in: ``SecretsStore.default()`` returns a
store wired to a ``KeyfileEncryption`` instance whose master key lives in
``~/.serena/secrets.key`` (chmod 600, autogenerated on first encrypted
write). Set ``SERENA_SECRETS_DISABLE_ENCRYPTION=1`` to force plaintext for
test environments. Set ``SERENA_SECRETS_PASSPHRASE=<…>`` to derive the key
from a passphrase via scrypt instead — the salt is stored in the DB so
the same passphrase keeps producing the same data-encryption key.

Backward compatibility: rows written before encryption was introduced
carry ``cipher = 'plain'`` and remain readable. A new encrypted write to
the same (scope, key) transparently re-encrypts; ``rotate_encryption``
walks the store to re-encrypt all legacy rows in one go.
"""

from __future__ import annotations

import contextlib
import os
import sqlite3
import threading
from pathlib import Path
from typing import Iterator

from serena.config.serena_config import SerenaPaths
from serena.util.secrets_crypto import (
    CIPHER_AES_GCM_V1,
    CIPHER_PLAIN,
    Encryption,
    KeyfileEncryption,
    PassphraseEncryption,
    PlainEncryption,
)

SECRETS_DB_FILENAME = "secrets.sqlite3"
"""Default basename under SerenaPaths().serena_user_home_dir."""

SECRETS_KEYFILE_FILENAME = "secrets.key"
"""Master key file for KeyfileEncryption, sibling to the DB."""

MASK_VISIBLE_PREFIX = 4
MASK_VISIBLE_SUFFIX = 4
"""When masking, keep the leading and trailing N chars verbatim."""

_SCHEMA = """
CREATE TABLE IF NOT EXISTS secrets (
    scope       TEXT NOT NULL,
    key         TEXT NOT NULL,
    value       TEXT NOT NULL,
    cipher      TEXT NOT NULL DEFAULT 'plain',
    updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    PRIMARY KEY (scope, key)
) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS store_meta (
    key   TEXT PRIMARY KEY,
    value BLOB
);
"""

_META_PASSPHRASE_SALT_KEY = "passphrase_salt"


def mask_secret(value: str | None) -> str:
    """Return a masked representation safe for UI / logs.

    Short values (<= visible prefix + suffix + 4) collapse to ``"****"`` to
    avoid leaking via length-revealing patterns on tiny secrets.
    """
    if value is None or value == "":
        return ""
    threshold = MASK_VISIBLE_PREFIX + MASK_VISIBLE_SUFFIX + 4
    if len(value) <= threshold:
        return "****"
    return value[:MASK_VISIBLE_PREFIX] + "****" + value[-MASK_VISIBLE_SUFFIX:]


class SecretsStore:
    """SQLite-backed key/value store scoped by ``scope`` (e.g. ``"r2"``).

    Pass an ``encryption`` strategy (default ``PlainEncryption`` to keep
    the constructor backwards-compatible with existing tests). Production
    callers should use ``SecretsStore.default()`` which selects an
    appropriate encryption based on the environment.
    """

    def __init__(
        self,
        path: str | os.PathLike[str] | None = None,
        encryption: Encryption | None = None,
    ) -> None:
        if path is None:
            path = Path(SerenaPaths().serena_user_home_dir) / SECRETS_DB_FILENAME
        self._path = Path(path)
        self._encryption: Encryption = encryption or PlainEncryption()
        # In-process lock so concurrent writers in the same Serena instance
        # serialise their schema-init + insert/update path without depending
        # on SQLite's BEGIN IMMEDIATE upgrade dance.
        self._lock = threading.Lock()
        self._ensure_storage()

    # ---- construction ------------------------------------------------------

    @classmethod
    def default(
        cls,
        path: str | os.PathLike[str] | None = None,
        *,
        passphrase: str | None = None,
    ) -> "SecretsStore":
        """Construct a SecretsStore with the recommended encryption mode.

        Precedence:
          1. ``SERENA_SECRETS_DISABLE_ENCRYPTION=1`` → plain (test escape hatch).
          2. ``passphrase`` argument or ``SERENA_SECRETS_PASSPHRASE`` env →
             PassphraseEncryption (scrypt-derived key, salt stored in DB).
          3. otherwise → KeyfileEncryption (autogenerated chmod-600 keyfile).
        """
        resolved_path = (
            Path(path)
            if path is not None
            else Path(SerenaPaths().serena_user_home_dir) / SECRETS_DB_FILENAME
        )
        if os.environ.get("SERENA_SECRETS_DISABLE_ENCRYPTION") == "1":
            return cls(resolved_path, encryption=PlainEncryption())

        env_pass = passphrase or os.environ.get("SERENA_SECRETS_PASSPHRASE")
        if env_pass:
            # Open a barebones store first so we can fetch / generate the salt.
            store = cls(resolved_path, encryption=PlainEncryption())
            salt = store._get_or_create_passphrase_salt()
            store._encryption = PassphraseEncryption.derive(env_pass, salt)
            return store

        keyfile = resolved_path.with_name(SECRETS_KEYFILE_FILENAME)
        return cls(resolved_path, encryption=KeyfileEncryption.load_or_create(keyfile))

    # ---- introspection -----------------------------------------------------

    @property
    def path(self) -> Path:
        return self._path

    @property
    def encryption(self) -> Encryption:
        return self._encryption

    @property
    def encryption_label(self) -> str:
        """Stable label for the dashboard ("plain", "aes-gcm-v1")."""
        return self._encryption.cipher_id

    # ---- storage / migration ----------------------------------------------

    def _ensure_storage(self) -> None:
        parent = self._path.parent
        parent.mkdir(parents=True, exist_ok=True)
        with contextlib.suppress(OSError):
            os.chmod(parent, 0o700)
        new_db = not self._path.exists()
        with self._connect() as conn:
            conn.executescript(_SCHEMA)
            self._migrate(conn)
        if new_db:
            with contextlib.suppress(OSError):
                os.chmod(self._path, 0o600)

    def _migrate(self, conn: sqlite3.Connection) -> None:
        """Apply additive schema migrations idempotently."""
        cols = {row[1] for row in conn.execute("PRAGMA table_info(secrets)").fetchall()}
        if "cipher" not in cols:
            # Pre-encryption schema: add the column and backfill 'plain' so
            # existing rows are still readable through the same code path.
            conn.execute("ALTER TABLE secrets ADD COLUMN cipher TEXT NOT NULL DEFAULT 'plain'")
            conn.execute("UPDATE secrets SET cipher = 'plain' WHERE cipher IS NULL OR cipher = ''")

    @contextlib.contextmanager
    def _connect(self) -> Iterator[sqlite3.Connection]:
        conn = sqlite3.connect(str(self._path), timeout=10.0)
        try:
            conn.execute("PRAGMA journal_mode=WAL")
            conn.execute("PRAGMA foreign_keys=ON")
            yield conn
            conn.commit()
        except BaseException:
            conn.rollback()
            raise
        finally:
            conn.close()

    def _get_or_create_passphrase_salt(self) -> bytes:
        with self._lock, self._connect() as conn:
            row = conn.execute(
                "SELECT value FROM store_meta WHERE key = ?",
                (_META_PASSPHRASE_SALT_KEY,),
            ).fetchone()
            if row and row[0]:
                return bytes(row[0])
            salt = PassphraseEncryption.new_salt()
            conn.execute(
                "INSERT OR REPLACE INTO store_meta(key, value) VALUES(?, ?)",
                (_META_PASSPHRASE_SALT_KEY, salt),
            )
            return salt

    # ---- read / write ------------------------------------------------------

    def set_secret(self, scope: str, key: str, value: str) -> None:
        if not scope or not key:
            raise ValueError("scope and key must be non-empty")
        encoded = self._encryption.encrypt(value, scope=scope, key=key)
        cipher = self._encryption.cipher_id
        with self._lock, self._connect() as conn:
            conn.execute(
                "INSERT INTO secrets(scope, key, value, cipher) VALUES(?, ?, ?, ?) "
                "ON CONFLICT(scope, key) DO UPDATE SET "
                "value = excluded.value, "
                "cipher = excluded.cipher, "
                "updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')",
                (scope, key, encoded, cipher),
            )

    def _decode(self, scope: str, key: str, value: str, cipher: str) -> str:
        if cipher == CIPHER_PLAIN:
            return PlainEncryption().decrypt(value, scope=scope, key=key)
        if cipher == self._encryption.cipher_id:
            return self._encryption.decrypt(value, scope=scope, key=key)
        # Unknown cipher: the row was written by a different encryption mode
        # than the one configured now. Don't silently corrupt it — surface
        # the mismatch so the operator can rotate.
        raise RuntimeError(
            f"secret ({scope!r}, {key!r}) stored with cipher {cipher!r} but active "
            f"encryption is {self._encryption.cipher_id!r}; run rotate_encryption()"
        )

    def get_secret(self, scope: str, key: str) -> str | None:
        with self._connect() as conn:
            row = conn.execute(
                "SELECT value, cipher FROM secrets WHERE scope = ? AND key = ?",
                (scope, key),
            ).fetchone()
        if not row:
            return None
        return self._decode(scope, key, row[0], row[1])

    def list_scope(self, scope: str) -> dict[str, str]:
        """Return all key→value pairs in a scope, decrypted. Mask at boundary."""
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT key, value, cipher FROM secrets WHERE scope = ? ORDER BY key",
                (scope,),
            ).fetchall()
        return {k: self._decode(scope, k, v, c) for k, v, c in rows}

    def list_scope_masked(self, scope: str) -> dict[str, str]:
        return {k: mask_secret(v) for k, v in self.list_scope(scope).items()}

    def list_scope_with_cipher(self, scope: str) -> list[tuple[str, str, str]]:
        """Return (key, decoded_value, cipher) for diagnostics / rotation."""
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT key, value, cipher FROM secrets WHERE scope = ? ORDER BY key",
                (scope,),
            ).fetchall()
        return [(k, self._decode(scope, k, v, c), c) for k, v, c in rows]

    def list_scopes(self) -> list[str]:
        with self._connect() as conn:
            rows = conn.execute("SELECT DISTINCT scope FROM secrets ORDER BY scope").fetchall()
        return [r[0] for r in rows]

    def delete_secret(self, scope: str, key: str) -> bool:
        with self._lock, self._connect() as conn:
            cur = conn.execute(
                "DELETE FROM secrets WHERE scope = ? AND key = ?",
                (scope, key),
            )
            return cur.rowcount > 0

    def delete_scope(self, scope: str) -> int:
        with self._lock, self._connect() as conn:
            cur = conn.execute("DELETE FROM secrets WHERE scope = ?", (scope,))
            return cur.rowcount

    # ---- rotation ----------------------------------------------------------

    def rotate_encryption(self) -> int:
        """Re-encrypt every row to the currently-active encryption.

        Returns the number of rows rewritten. Rows already at the active
        cipher are left untouched; legacy ``plain`` rows are upgraded.
        Idempotent — running twice is a no-op on the second pass.
        """
        rewritten = 0
        with self._lock, self._connect() as conn:
            rows = conn.execute("SELECT scope, key, value, cipher FROM secrets").fetchall()
            target = self._encryption.cipher_id
            for scope, key, value, cipher in rows:
                if cipher == target:
                    continue
                plaintext = self._decode(scope, key, value, cipher)
                encoded = self._encryption.encrypt(plaintext, scope=scope, key=key)
                conn.execute(
                    "UPDATE secrets SET value = ?, cipher = ?, "
                    "updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') "
                    "WHERE scope = ? AND key = ?",
                    (encoded, target, scope, key),
                )
                rewritten += 1
        return rewritten


__all__ = [
    "SecretsStore",
    "mask_secret",
    "SECRETS_DB_FILENAME",
    "SECRETS_KEYFILE_FILENAME",
    "CIPHER_PLAIN",
    "CIPHER_AES_GCM_V1",
]
